#! /bin/sh
# /etc/init.d/choose_repo
#
### BEGIN INIT INFO
# Provides: choose_repo
# Defalt-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Description: Initializes the correct repo depending on the region.
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

case "$1" in
    start)
        echo -n $"Starting splice-init: "
        /usr/bin/splice-init && success || failure
        echo
	;;
esac

exit 0
